[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[window]
option_as_alt = "OnlyRight"
opacity = 0.7
blur = true 

[font]
normal = { family = "0xProtoNerdFont", style = "Italic"}
bold = { family = "0xProtoNerdFont", style = "Bold"}
italic = { family = "0xProtoNerdFont", style = "Italic"}
bold_italic = { family = "0xProtoNerdFont", style = "Bold Italic"}
size = 10.5
